# Generated by Django 3.1.7 on 2022-04-30 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sendername', models.CharField(max_length=50)),
                ('Sendermail', models.CharField(max_length=50)),
                ('Sendersub', models.CharField(max_length=50)),
                ('Sendermess', models.CharField(max_length=50)),
                ('SendingTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
